#!/usr/bin/env tsx
/**
 * Regenerates `src/types.gen.ts` from the committed `openapi.json` snapshot.
 *
 * This does NOT talk to a running node — it only reads the local snapshot, so
 * it is safe to run offline / in CI. To pick up server-side API changes, run
 * `bun run fetch-openapi` first (needs a dev node), review the `openapi.json`
 * diff, then run this.
 *
 * Usage: tsx scripts/generate.ts
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import openapiTS, { astToString } from "openapi-typescript";
import { dedupeOperationIds } from "./prepare-spec";

const packageRoot = join(dirname(fileURLToPath(import.meta.url)), "..");
const specPath = join(packageRoot, "openapi.json");
const outPath = join(packageRoot, "src", "types.gen.ts");

export async function generateTypesSource(): Promise<string> {
  const spec = dedupeOperationIds(JSON.parse(readFileSync(specPath, "utf-8")));
  const ast = await openapiTS(spec, {
    // Keep generation deterministic and dependency-free at consume time.
    exportType: false,
  });
  const body = astToString(ast);
  const header = [
    "/* eslint-disable */",
    "// AUTO-GENERATED by packages/api-client/scripts/generate.ts — do not edit by hand.",
    "// Source: packages/api-client/openapi.json (StingStream.Core /stingstream/api/v1/openapi.json).",
    "// Regenerate: bun run fetch-openapi && bun run generate  (see README.md).",
    "",
  ].join("\n");
  return `${header}${body}`;
}

async function main() {
  const source = await generateTypesSource();
  writeFileSync(outPath, source, "utf-8");
  console.log(`Wrote ${outPath}.`);
}

const isMain =
  process.argv[1] !== undefined &&
  fileURLToPath(import.meta.url) === resolve(process.argv[1]);

if (isMain) {
  main().catch((err) => {
    console.error(err);
    process.exit(1);
  });
}
