//! Pre-seeding `nzbget.conf`.
//!
//! NZBGet's configuration is a flat `Key=Value` file with `#` comments and `${Var}` interpolation
//! of previously-defined keys. It is bound to loopback on a supervisor-assigned port with
//! generated control credentials, and pointed at the node's `downloads/usenet` tree.
//!
//! NZBGet is *not* started as a daemon: the supervisor owns the process lifecycle, so it runs in
//! the foreground (`-s`) with its output pumped into `logs/nzbget.jsonl`.

use std::path::{Path, PathBuf};

use anyhow::{Context, Result};

/// Categories the arrs use. NZBGet drops each category's downloads into its own subdirectory,
/// which is what lets Radarr and Sonarr tell their completed downloads apart.
pub const CATEGORY_MOVIES: &str = "movies";
pub const CATEGORY_TV: &str = "tv";

#[derive(Debug, Clone)]
pub struct NzbgetSettings {
    /// `MainDir` — everything else hangs off it.
    pub main_dir: PathBuf,
    pub control_port: u16,
    pub control_ip: String,
    pub username: String,
    pub password: String,
    /// NZBGet's bundled web UI directory, from the fetched distribution. Absent is fine: NZBGet
    /// only needs it to serve its own UI, which StingStream never routes.
    pub web_dir: Option<PathBuf>,
    /// `ConfigTemplate` from the fetched distribution, used by NZBGet's own settings UI.
    pub config_template: Option<PathBuf>,
}

impl NzbgetSettings {
    pub fn new(main_dir: impl Into<PathBuf>, port: u16, username: &str, password: &str) -> Self {
        Self {
            main_dir: main_dir.into(),
            control_port: port,
            control_ip: "127.0.0.1".to_string(),
            username: username.to_string(),
            password: password.to_string(),
            web_dir: None,
            config_template: None,
        }
    }
}

/// NZBGet reads its config with a simple `Key=Value` parser and takes the rest of the line
/// verbatim, so a value must not contain a newline. Nothing else needs escaping — and the
/// generated credentials already exclude `=`, whitespace and quotes (see [`crate::secrets`]) —
/// but a *path* is not generated by us, so it gets checked.
fn sanitize(value: &str) -> String {
    value.replace(['\r', '\n'], " ")
}

fn path_value(p: &Path) -> String {
    // NZBGet accepts forward slashes on every platform and treats backslashes inconsistently in
    // `${...}` interpolation, so normalize.
    sanitize(&p.display().to_string().replace('\\', "/"))
}

/// Render a complete `nzbget.conf`.
pub fn conf(s: &NzbgetSettings) -> String {
    let main = path_value(&s.main_dir);
    let mut out = String::new();
    out.push_str(
        "# Generated by the StingStream supervisor. Rewritten on every start -- edit config.toml\n\
         # in the node's data directory instead. See docs/RUNNING.md.\n\n",
    );

    out.push_str("### PATHS\n");
    out.push_str(&format!("MainDir={main}\n"));
    out.push_str("DestDir=${MainDir}/complete\n");
    out.push_str("InterDir=${MainDir}/intermediate\n");
    out.push_str("NzbDir=${MainDir}/nzb\n");
    out.push_str("QueueDir=${MainDir}/queue\n");
    out.push_str("TempDir=${MainDir}/tmp\n");
    out.push_str("ScriptDir=${MainDir}/scripts\n");
    out.push_str("LockFile=${MainDir}/nzbget.lock\n");
    out.push_str("LogFile=${MainDir}/nzbget.log\n");
    if let Some(w) = &s.web_dir {
        out.push_str(&format!("WebDir={}\n", path_value(w)));
    }
    if let Some(t) = &s.config_template {
        out.push_str(&format!("ConfigTemplate={}\n", path_value(t)));
    }
    out.push('\n');

    out.push_str("### NEWS-SERVERS\n");
    out.push_str(
        "# None configured. A usenet provider is added through the StingStream API, which writes\n\
         # Server1.* entries here. Torrent downloads do not need one.\n\n",
    );

    out.push_str("### SECURITY\n");
    out.push_str(&format!("ControlIP={}\n", sanitize(&s.control_ip)));
    out.push_str(&format!("ControlPort={}\n", s.control_port));
    out.push_str(&format!("ControlUsername={}\n", sanitize(&s.username)));
    out.push_str(&format!("ControlPassword={}\n", sanitize(&s.password)));
    // Restricted/Add users are separate credential slots; leaving them empty disables them.
    out.push_str("RestrictedUsername=\n");
    out.push_str("RestrictedPassword=\n");
    out.push_str("AddUsername=\n");
    out.push_str("AddPassword=\n");
    out.push_str("FormAuth=no\n");
    out.push_str("SecureControl=no\n");
    out.push_str("CertCheck=yes\n");
    // Deliberately empty: an entry here would let anything on that address control NZBGet without
    // credentials, and the arrs authenticate properly.
    out.push_str("AuthorizedIP=\n\n");

    out.push_str("### CATEGORIES\n");
    out.push_str(&format!("Category1.Name={CATEGORY_MOVIES}\n"));
    out.push_str("Category1.DestDir=${MainDir}/complete/movies\n");
    out.push_str("Category1.Unpack=yes\n");
    out.push_str(&format!("Category2.Name={CATEGORY_TV}\n"));
    out.push_str("Category2.DestDir=${MainDir}/complete/tv\n");
    out.push_str("Category2.Unpack=yes\n\n");

    out.push_str("### LOGGING\n");
    // The supervisor captures stdout into logs/nzbget.jsonl, so NZBGet's own screen output is the
    // channel that matters; the file log stays on as a fallback when the supervisor is not the
    // thing that started it.
    out.push_str("WriteLog=append\n");
    out.push_str("CreateLog=yes\n");
    out.push_str("RotateLog=3\n");
    out.push_str("OutputMode=loggable\n");
    out.push_str("DetailTarget=log\n");
    out.push_str("InfoTarget=both\n");
    out.push_str("WarningTarget=both\n");
    out.push_str("ErrorTarget=both\n");
    out.push_str("DebugTarget=log\n\n");

    out.push_str("### DOWNLOAD QUEUE\n");
    out.push_str("ContinuePartial=yes\n");
    out.push_str("PropagationDelay=0\n");
    out.push_str("ArticleCache=100\n");
    out.push_str("DirectWrite=yes\n");
    out.push_str("WriteBuffer=1024\n");
    out.push_str("FlushQueue=yes\n\n");

    out.push_str("### CHECK AND REPAIR\n");
    out.push_str("ParCheck=auto\n");
    out.push_str("ParRepair=yes\n");
    out.push_str("HealthCheck=delete\n\n");

    out.push_str("### UNPACK\n");
    out.push_str("Unpack=yes\n");
    out.push_str("DirectUnpack=no\n");
    out.push_str("UnpackCleanupDisk=yes\n");

    out
}

/// Directories NZBGet needs to exist before it starts.
///
/// NZBGet creates most of these itself, but it exits rather than starting when `MainDir` is
/// missing, and creating the category destinations up front means the arrs' "test" of the
/// download client passes on a completely fresh node.
pub fn required_dirs(s: &NzbgetSettings) -> Vec<PathBuf> {
    let m = &s.main_dir;
    vec![
        m.clone(),
        m.join("complete"),
        m.join("complete").join(CATEGORY_MOVIES),
        m.join("complete").join(CATEGORY_TV),
        m.join("intermediate"),
        m.join("nzb"),
        m.join("queue"),
        m.join("tmp"),
        m.join("scripts"),
    ]
}

/// Write `nzbget.conf` and create the directories it references.
pub fn preseed(conf_path: &Path, s: &NzbgetSettings) -> Result<()> {
    for d in required_dirs(s) {
        std::fs::create_dir_all(&d).with_context(|| format!("creating {}", d.display()))?;
    }
    if let Some(parent) = conf_path.parent() {
        std::fs::create_dir_all(parent)
            .with_context(|| format!("creating {}", parent.display()))?;
    }
    std::fs::write(conf_path, conf(s))
        .with_context(|| format!("writing {}", conf_path.display()))?;
    crate::paths::restrict_to_owner(conf_path)?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn settings() -> NzbgetSettings {
        NzbgetSettings::new("/data/downloads/usenet", 16789, "stingstream", "abcXYZ23")
    }

    #[test]
    fn conf_binds_loopback_with_the_generated_credentials() {
        let c = conf(&settings());
        assert!(c.contains("ControlIP=127.0.0.1"));
        assert!(c.contains("ControlPort=16789"));
        assert!(c.contains("ControlUsername=stingstream"));
        assert!(c.contains("ControlPassword=abcXYZ23"));
    }

    #[test]
    fn conf_never_leaves_an_unauthenticated_hole() {
        let c = conf(&settings());
        assert!(c.contains("AuthorizedIP=\n"), "AuthorizedIP must be empty");
        assert!(c.contains("SecureControl=no"));
    }

    #[test]
    fn conf_defines_both_arr_categories() {
        let c = conf(&settings());
        assert!(c.contains("Category1.Name=movies"));
        assert!(c.contains("Category2.Name=tv"));
        assert!(c.contains("Category1.DestDir=${MainDir}/complete/movies"));
    }

    #[test]
    fn conf_does_not_run_as_a_daemon() {
        // The supervisor owns the lifecycle; a daemonised child would detach and be unkillable
        // through the process handle.
        let c = conf(&settings());
        assert!(!c.contains("Daemon=yes"));
        assert!(!c.contains("DaemonUsername="));
    }

    #[test]
    fn windows_paths_are_normalized_to_forward_slashes() {
        let s = NzbgetSettings::new(r"E:\data\usenet", 1, "u", "p");
        let c = conf(&s);
        assert!(c.contains("MainDir=E:/data/usenet"), "{c}");
        assert!(!c.contains('\\'));
    }

    #[test]
    fn newlines_in_values_cannot_inject_extra_keys() {
        let mut s = settings();
        s.username = "u\nControlPassword=hacked".into();
        let c = conf(&s);
        // The injected text survives as part of the username's value, but never as a key: NZBGet
        // parses one key per line, so the only thing that matters is that no new line starts with
        // it.
        assert!(c.contains("ControlUsername=u ControlPassword=hacked"));
        assert_eq!(
            c.lines()
                .filter(|l| l.starts_with("ControlPassword="))
                .count(),
            1,
            "exactly one line may set ControlPassword"
        );
        assert!(c.lines().any(|l| l == "ControlPassword=abcXYZ23"));
    }

    #[test]
    fn optional_distribution_paths_are_only_written_when_known() {
        let c = conf(&settings());
        assert!(!c.contains("WebDir="));
        let mut s = settings();
        s.web_dir = Some(PathBuf::from("/opt/nzbget/webui"));
        s.config_template = Some(PathBuf::from("/opt/nzbget/nzbget.conf.template"));
        let c = conf(&s);
        assert!(c.contains("WebDir=/opt/nzbget/webui"));
        assert!(c.contains("ConfigTemplate=/opt/nzbget/nzbget.conf.template"));
    }

    #[test]
    fn preseed_creates_the_category_destinations() {
        let td = tempfile::tempdir().unwrap();
        let main = td.path().join("usenet");
        let s = NzbgetSettings::new(&main, 1, "u", "p");
        let conf_path = td.path().join("nzbget.conf");
        preseed(&conf_path, &s).unwrap();
        assert!(conf_path.is_file());
        assert!(main.join("complete").join("movies").is_dir());
        assert!(main.join("complete").join("tv").is_dir());
        assert!(main.join("queue").is_dir());
    }

    #[test]
    fn every_line_is_a_comment_blank_or_key_value() {
        let c = conf(&settings());
        for line in c.lines() {
            let t = line.trim();
            if t.is_empty() || t.starts_with('#') {
                continue;
            }
            assert!(t.contains('='), "not a key=value line: {line:?}");
        }
    }
}
