using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text.Json.Nodes;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MonoTorrent.Client;
using StingStream.Core.Configuration;
using StingStream.Core.Federated;

namespace StingStream.Core.Torrents;

/// <summary>
/// A qBittorrent-compatible API subset, so Radarr and Sonarr can drive StingStream's in-process
/// torrent engine with their own stock, unpatched qBittorrent download client.
/// </summary>
/// <remarks>
/// Served at <c>/stingstream/qbt/api/v2/*</c> -- which, because Jellyfin maps every route under its
/// <c>BaseUrl</c>, is really <c>/jellyfin/stingstream/qbt/api/v2/*</c>. The supervisor writes that
/// whole prefix into <c>runtime.json</c> as <c>qbittorrent.url_base</c>, and
/// <see cref="Arr.OmniarrSyncService"/> configures both apps with it.
///
/// The surface is exactly what Radarr's and Sonarr's <c>QBittorrentProxyV2</c> actually calls,
/// verified against <c>server/radarr/src/NzbDrone.Core/Download/Clients/QBittorrent/</c>. Three
/// details in there are load-bearing and easy to get wrong:
///
/// * <c>app/webapiVersion</c> must answer *without* authentication and must not 404. That single
///   response is how the arrs choose the v2 proxy over the ancient v1 one, and the body has to
///   parse with .NET's <c>Version.Parse</c> -- no "v" prefix, no extra text.
/// * A completed torrent's <c>content_path</c> must differ from its <c>save_path</c>. When they
///   match, both apps mark the download as a *warning* and never import it.
/// * The <c>state</c> string drives everything: <c>stoppedUP</c>/<c>uploading</c> mean "ready to
///   import", <c>stalledDL</c> means "warn the user". <see cref="QbtState"/> holds the mapping.
///
/// Authentication is qBittorrent's own: a form login that returns an opaque <c>SID</c> cookie.
/// The credentials are generated by the supervisor and live in <c>runtime.json</c>.
/// </remarks>
[ApiController]
[AllowAnonymous]
[Route("stingstream/qbt/api/v2")]
[ApiExplorerSettings(IgnoreApi = true)]
public sealed class QbtController : ControllerBase
{
    /// <summary>Named <see cref="System.Net.Http.IHttpClientFactory"/> client for fetching .torrent URLs.</summary>
    public const string HttpClientName = "StingStream.Qbt";

    /// <summary>
    /// The Web API version reported to the arrs.
    /// </summary>
    /// <remarks>
    /// Chosen deliberately. Above 2.6.1, so the arrs use <c>content_path</c> to locate a finished
    /// download rather than reconstructing it from <c>torrents/files</c>; above 2.8.1, so share
    /// limits ride along on the add; and below 2.11.0, where qBittorrent renamed the add form's
    /// <c>paused</c> parameter to <c>stopped</c> and the arrs switch with it.
    /// </remarks>
    public const string WebApiVersion = "2.9.3";

    /// <summary>The application version reported to the arrs. Display only; nothing parses it.</summary>
    public const string AppVersion = "v4.6.7";

    /// <summary>Cookie name qBittorrent uses for its session. The arrs replay whatever we set.</summary>
    public const string SessionCookie = "SID";

    private readonly TorrentEngine _engine;
    private readonly QbtSessionStore _sessions;
    private readonly INodeRuntimeProvider _runtime;
    private readonly ILogger<QbtController> _logger;

    public QbtController(
        TorrentEngine engine,
        QbtSessionStore sessions,
        INodeRuntimeProvider runtime,
        ILogger<QbtController> logger)
    {
        _engine = engine;
        _sessions = sessions;
        _runtime = runtime;
        _logger = logger;
    }

    // --- authentication ----------------------------------------------------

    /// <summary>qBittorrent's form login.</summary>
    [HttpPost("auth/login")]
    [Consumes("application/x-www-form-urlencoded", "multipart/form-data")]
    public IActionResult Login([FromForm] string? username, [FromForm] string? password)
    {
        var creds = _runtime.Current?.Qbittorrent;
        if (creds is null)
        {
            _logger.LogWarning("A qBittorrent login arrived but runtime.json has no credentials");
            return Content("Fails.", "text/plain");
        }

        // Ordinal comparison, no trimming: these are generated secrets, not user input.
        var ok = string.Equals(username, creds.Username, StringComparison.Ordinal)
            && string.Equals(password, creds.Password, StringComparison.Ordinal);
        if (!ok)
        {
            _logger.LogWarning("Rejected a qBittorrent login for user {User}", username);
            return Content("Fails.", "text/plain");
        }

        var sid = _sessions.Create();
        Response.Cookies.Append(
            SessionCookie,
            sid,
            new CookieOptions
            {
                Path = "/",
                HttpOnly = true,
                // The arrs reach this over loopback HTTP; marking the cookie Secure would stop it
                // being sent back at all.
                Secure = false,
                SameSite = SameSiteMode.Lax,
            });
        return Content("Ok.", "text/plain");
    }

    /// <summary>Ends a session. qBittorrent has this; the arrs never call it.</summary>
    [HttpPost("auth/logout")]
    public IActionResult Logout()
    {
        if (Request.Cookies.TryGetValue(SessionCookie, out var sid))
        {
            _sessions.Remove(sid);
        }

        return Content("Ok.", "text/plain");
    }

    /// <summary>
    /// Reports whether this request carries a valid session.
    /// </summary>
    /// <remarks>
    /// Returns 403, never 401. The arrs treat a 403 as "log in again and retry" and a 401 as a
    /// hard authentication failure that aborts the whole operation.
    /// </remarks>
    private bool Authenticated()
    {
        var creds = _runtime.Current?.Qbittorrent;
        if (creds is null || string.IsNullOrEmpty(creds.Password))
        {
            // **Fail closed.** This used to return true, on the reasoning that qBittorrent itself
            // treats an empty username and password as "no authentication". qBittorrent is a
            // program a person installed and configured; this is a shim that is always configured,
            // by the supervisor, in runtime.json. So the only ways to reach this branch are that
            // runtime.json is missing, unreadable, or has not been written yet -- and every one of
            // those is a *fault*, not a decision, and the thing on the other side of it is
            // "add any torrent, to any path, and delete files". A fault must not open the door.
            //
            // The cost of being wrong the other way is small and loud: the arrs log a failed
            // download-client test and the supervisor's log says why.
            _logger.LogWarning(
                "Refusing a qBittorrent API call: runtime.json has no credentials for it yet");
            return false;
        }

        return Request.Cookies.TryGetValue(SessionCookie, out var sid) && _sessions.IsValid(sid);
    }

    /// <summary>
    /// The save path to use for an add, or null when the caller asked for one it may not have.
    /// </summary>
    /// <remarks>
    /// <c>savepath</c> arrives from the caller and used to be handed to MonoTorrent verbatim, which
    /// made this endpoint an arbitrary-file-write primitive: an add with
    /// <c>savepath=C:\Windows\System32</c> would have MonoTorrent create directories and write
    /// torrent contents there, as whatever account the node runs as. The arrs only ever send a path
    /// the node itself told them about, so nothing legitimate is lost by requiring it to be inside
    /// the torrent root.
    ///
    /// <see cref="SafePath.IsUnder"/> is the same containment check the federated materializer uses
    /// on peer-supplied titles, and for the same reason: it canonicalises both sides before
    /// comparing, so <c>..</c>, a symlink, a UNC path and a short 8.3 name all resolve to what they
    /// really are first.
    /// </remarks>
    private string? ResolveSavePath(string? requested, string? category)
    {
        if (string.IsNullOrWhiteSpace(requested))
        {
            return _engine.SavePathFor(category);
        }

        if (!SafePath.IsUnder(_engine.Root, requested))
        {
            _logger.LogWarning(
                "Refusing a qBittorrent add with a save path outside the torrent root: {Path}",
                requested);
            return null;
        }

        return requested;
    }

    private IActionResult? Unauthorised()
        => Authenticated() ? null : StatusCode(StatusCodes.Status403Forbidden, "Forbidden");

    // --- application ------------------------------------------------------

    /// <summary>
    /// The Web API version. Deliberately anonymous: this is the arrs' probe for whether a v2 API
    /// exists at all, and it happens before any login.
    /// </summary>
    [HttpGet("app/webapiVersion")]
    public IActionResult WebApiVersionEndpoint() => Content(WebApiVersion, "text/plain");

    /// <summary>The application version. Display only.</summary>
    [HttpGet("app/version")]
    public IActionResult Version()
        => Unauthorised() ?? Content(AppVersion, "text/plain");

    /// <summary>
    /// Client preferences.
    /// </summary>
    /// <remarks>
    /// The arrs read exactly ten fields from this and validate two things with them: that the
    /// client is not configured to delete completed downloads before they can be imported
    /// (<c>max_ratio_enabled</c> / <c>max_seeding_time_enabled</c> combined with
    /// <c>max_ratio_act</c>), and that queueing is on when a non-default download priority is set.
    /// Every limit here is therefore reported as disabled: StingStream keeps seeding until the arr
    /// says the download may go.
    /// </remarks>
    [HttpGet("app/preferences")]
    public IActionResult Preferences()
    {
        var unauthorised = Unauthorised();
        if (unauthorised is not null)
        {
            return unauthorised;
        }

        var settings = new JsonObject
        {
            ["save_path"] = _engine.Root,
            ["temp_path_enabled"] = false,
            ["temp_path"] = _engine.Root,
            ["max_ratio_enabled"] = false,
            ["max_ratio"] = -1,
            ["max_seeding_time_enabled"] = false,
            ["max_seeding_time"] = -1,
            ["max_inactive_seeding_time_enabled"] = false,
            ["max_inactive_seeding_time"] = -1,
            // 0 = Pause. Never Remove or DeleteFiles: an engine that deletes a download on its own
            // schedule can delete it before the arr has imported it.
            ["max_ratio_act"] = 0,
            ["queueing_enabled"] = true,
            ["dht"] = DhtEnabled(),
            ["pex"] = true,
            ["lsd"] = true,
            ["auto_tmm_enabled"] = false,
            ["create_subfolder_enabled"] = true,
            ["start_paused_enabled"] = false,
        };
        return new JsonResult(settings);
    }

    private bool DhtEnabled()
    {
        // Reported honestly rather than hard-coded true. With DHT off the arrs refuse a
        // trackerless magnet immediately, which is the right answer -- this engine genuinely
        // cannot fetch one -- instead of accepting it and stalling in metaDL forever.
        return HttpContext.RequestServices
            .GetService(typeof(Data.SettingsStore)) is Data.SettingsStore store
            && store.Get().DownloadClients.TorrentDhtEnabled;
    }

    /// <summary>Build info. Present for completeness; the arrs do not call it.</summary>
    [HttpGet("app/buildInfo")]
    public IActionResult BuildInfo()
        => Unauthorised() ?? new JsonResult(new JsonObject
        {
            ["qt"] = "0.0.0",
            ["libtorrent"] = "0.0.0",
            ["boost"] = "0.0.0",
            ["openssl"] = "0.0.0",
            ["bitness"] = 64,
        });

    // --- torrents ---------------------------------------------------------

    /// <summary>The torrent list, optionally filtered by category.</summary>
    [HttpGet("torrents/info")]
    public IActionResult Info([FromQuery] string? category, [FromQuery] string? hashes)
    {
        var unauthorised = Unauthorised();
        if (unauthorised is not null)
        {
            return unauthorised;
        }

        var views = _engine.List(string.IsNullOrWhiteSpace(category) ? null : category);

        if (!string.IsNullOrWhiteSpace(hashes) && !string.Equals(hashes, "all", StringComparison.OrdinalIgnoreCase))
        {
            var wanted = hashes.Split('|', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries)
                .ToHashSet(StringComparer.OrdinalIgnoreCase);
            views = views.Where(v => wanted.Contains(v.Hash)).ToList();
        }

        var array = new JsonArray();
        foreach (var view in views)
        {
            array.Add(ToQbtTorrent(view));
        }

        return new JsonResult(array);
    }

    /// <summary>General properties of one torrent.</summary>
    [HttpGet("torrents/properties")]
    public IActionResult Properties([FromQuery] string hash)
    {
        var unauthorised = Unauthorised();
        if (unauthorised is not null)
        {
            return unauthorised;
        }

        var view = _engine.Find(hash);
        if (view is null)
        {
            // qBittorrent answers 404 here, and the arrs use exactly that to decide whether a
            // just-added torrent has landed yet.
            return NotFound();
        }

        return new JsonResult(new JsonObject
        {
            ["hash"] = view.Hash,
            ["save_path"] = view.SavePath,
            ["name"] = view.Name,
            ["total_size"] = view.Size,
            ["total_downloaded"] = view.Downloaded,
            ["total_uploaded"] = view.Uploaded,
            ["dl_speed"] = view.DownloadRate,
            ["up_speed"] = view.UploadRate,
            ["seeding_time"] = view.SeedingSeconds,
            ["share_ratio"] = view.Ratio,
            ["addition_date"] = view.AddedOn,
            ["completion_date"] = view.Complete ? view.AddedOn : -1,
            ["eta"] = Eta(view),
            ["nb_connections"] = 0,
            ["piece_size"] = 0,
        });
    }

    /// <summary>The files inside one torrent.</summary>
    [HttpGet("torrents/files")]
    public IActionResult Files([FromQuery] string hash)
    {
        var unauthorised = Unauthorised();
        if (unauthorised is not null)
        {
            return unauthorised;
        }

        var view = _engine.Find(hash);
        if (view is null)
        {
            return NotFound();
        }

        var array = new JsonArray();
        for (var i = 0; i < view.Files.Count; i++)
        {
            var f = view.Files[i];
            array.Add(new JsonObject
            {
                ["index"] = i,
                ["name"] = f.Path,
                ["size"] = f.Size,
                ["progress"] = view.Progress,
                ["priority"] = 1,
                ["is_seed"] = view.Complete,
            });
        }

        return new JsonResult(array);
    }

    /// <summary>
    /// Add torrents, by URL/magnet or as uploaded <c>.torrent</c> files.
    /// </summary>
    /// <remarks>
    /// The arrs use both shapes: <c>AddFromMagnetLink</c> posts a magnet in <c>urls</c>, while
    /// <c>AddFromTorrentFile</c> downloads the .torrent itself and posts the bytes as a multipart
    /// <c>torrents</c> file.
    /// </remarks>
    [HttpPost("torrents/add")]
    [RequestSizeLimit(64 * 1024 * 1024)]
    public async Task<IActionResult> Add(CancellationToken cancellationToken)
    {
        var unauthorised = Unauthorised();
        if (unauthorised is not null)
        {
            return unauthorised;
        }

        if (!Request.HasFormContentType)
        {
            return Content("Fails.", "text/plain");
        }

        var form = await Request.ReadFormAsync(cancellationToken).ConfigureAwait(false);
        var category = form["category"].ToString();
        var savePath = form["savepath"].ToString();
        // qBittorrent renamed this parameter at Web API 2.11.0; we report 2.9.3, so the arrs send
        // "paused" -- but accepting both costs nothing and makes the shim usable by other clients.
        var paused = IsTrue(form["paused"]) || IsTrue(form["stopped"]);

        var resolved = ResolveSavePath(savePath, category);
        if (resolved is null)
        {
            return Content("Fails.", "text/plain");
        }

        savePath = resolved;

        var added = new List<string>();

        foreach (var file in form.Files)
        {
            if (file.Length == 0)
            {
                continue;
            }

            using var ms = new MemoryStream();
            await file.CopyToAsync(ms, cancellationToken).ConfigureAwait(false);
            try
            {
                added.Add(await _engine
                    .AddTorrentFileAsync(ms.ToArray(), category, savePath, paused, cancellationToken)
                    .ConfigureAwait(false));
            }
            catch (Exception ex) when (ex is TorrentException or IOException or InvalidOperationException)
            {
                _logger.LogError(ex, "Could not add the uploaded torrent {File}", file.FileName);
                return Content("Fails.", "text/plain");
            }
        }

        var urls = form["urls"].ToString();
        if (!string.IsNullOrWhiteSpace(urls))
        {
            foreach (var url in urls.Split(
                         new[] { '\n', '\r' },
                         StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries))
            {
                try
                {
                    added.Add(await _engine
                        .AddUrlAsync(url, category, savePath, paused, cancellationToken)
                        .ConfigureAwait(false));
                }
                catch (Exception ex) when (ex is TorrentException or IOException or System.Net.Http.HttpRequestException)
                {
                    _logger.LogError(ex, "Could not add the torrent URL");
                    return Content("Fails.", "text/plain");
                }
            }
        }

        if (added.Count == 0)
        {
            _logger.LogWarning("torrents/add carried neither a file nor a URL");
            return Content("Fails.", "text/plain");
        }

        // Make sure the category exists so a later torrents/categories reports it, which is what
        // the arrs' "Test" checks after creating one.
        if (!string.IsNullOrWhiteSpace(category))
        {
            await _engine.CreateCategoryAsync(category, savePath, cancellationToken).ConfigureAwait(false);
        }

        return Content("Ok.", "text/plain");
    }

    /// <summary>Remove torrents, optionally deleting their data.</summary>
    [HttpPost("torrents/delete")]
    public async Task<IActionResult> Delete(CancellationToken cancellationToken)
    {
        var unauthorised = Unauthorised();
        if (unauthorised is not null)
        {
            return unauthorised;
        }

        var form = await Request.ReadFormAsync(cancellationToken).ConfigureAwait(false);
        // Absent means false. The arrs omit the field entirely when keeping data, and treating
        // absence as "delete" would destroy a download that was only meant to stop seeding.
        var deleteFiles = IsTrue(form["deleteFiles"]);

        foreach (var hash in SplitHashes(form["hashes"]))
        {
            await _engine.RemoveAsync(hash, deleteFiles, cancellationToken).ConfigureAwait(false);
        }

        return Ok();
    }

    /// <summary>Pause torrents. <c>torrents/stop</c> is qBittorrent 5's name for the same thing.</summary>
    [HttpPost("torrents/pause")]
    [HttpPost("torrents/stop")]
    public async Task<IActionResult> Pause(CancellationToken cancellationToken)
    {
        var unauthorised = Unauthorised();
        if (unauthorised is not null)
        {
            return unauthorised;
        }

        var form = await Request.ReadFormAsync(cancellationToken).ConfigureAwait(false);
        foreach (var hash in SplitHashes(form["hashes"]))
        {
            await _engine.PauseAsync(hash, cancellationToken).ConfigureAwait(false);
        }

        return Ok();
    }

    /// <summary>Resume torrents. <c>torrents/start</c> is qBittorrent 5's name for the same thing.</summary>
    [HttpPost("torrents/resume")]
    [HttpPost("torrents/start")]
    public async Task<IActionResult> Resume(CancellationToken cancellationToken)
    {
        var unauthorised = Unauthorised();
        if (unauthorised is not null)
        {
            return unauthorised;
        }

        var form = await Request.ReadFormAsync(cancellationToken).ConfigureAwait(false);
        foreach (var hash in SplitHashes(form["hashes"]))
        {
            await _engine.ResumeAsync(hash, cancellationToken).ConfigureAwait(false);
        }

        return Ok();
    }

    /// <summary>Move torrents into a category. The arrs use this to mark a download as imported.</summary>
    [HttpPost("torrents/setCategory")]
    public async Task<IActionResult> SetCategory(CancellationToken cancellationToken)
    {
        var unauthorised = Unauthorised();
        if (unauthorised is not null)
        {
            return unauthorised;
        }

        var form = await Request.ReadFormAsync(cancellationToken).ConfigureAwait(false);
        var category = form["category"].ToString();
        await _engine.CreateCategoryAsync(category, null, cancellationToken).ConfigureAwait(false);
        foreach (var hash in SplitHashes(form["hashes"]))
        {
            await _engine.SetCategoryAsync(hash, category, cancellationToken).ConfigureAwait(false);
        }

        return Ok();
    }

    /// <summary>Every category and its save path.</summary>
    [HttpGet("torrents/categories")]
    public IActionResult Categories()
    {
        var unauthorised = Unauthorised();
        if (unauthorised is not null)
        {
            return unauthorised;
        }

        var result = new JsonObject();
        foreach (var (name, path) in _engine.Categories())
        {
            result[name] = new JsonObject
            {
                ["name"] = name,
                ["savePath"] = path,
            };
        }

        return new JsonResult(result);
    }

    /// <summary>
    /// Create a category.
    /// </summary>
    /// <remarks>
    /// Part of the arrs' "Test": if the configured category is missing they create it here and
    /// then re-read <c>torrents/categories</c>, failing the test outright if it still is not
    /// there. So this has to actually persist.
    /// </remarks>
    [HttpPost("torrents/createCategory")]
    public async Task<IActionResult> CreateCategory(CancellationToken cancellationToken)
    {
        var unauthorised = Unauthorised();
        if (unauthorised is not null)
        {
            return unauthorised;
        }

        var form = await Request.ReadFormAsync(cancellationToken).ConfigureAwait(false);
        var name = form["category"].ToString();
        if (string.IsNullOrWhiteSpace(name))
        {
            return BadRequest();
        }

        // Same containment rule as an add: a category is a directory this node will create and
        // write into, so the caller does not get to name one outside the torrent root.
        var savePath = form["savePath"].ToString();
        if (!string.IsNullOrWhiteSpace(savePath) && !SafePath.IsUnder(_engine.Root, savePath))
        {
            _logger.LogWarning(
                "Refusing a qBittorrent category with a save path outside the torrent root: {Path}",
                savePath);
            return BadRequest();
        }

        await _engine.CreateCategoryAsync(name, string.IsNullOrWhiteSpace(savePath) ? null : savePath, cancellationToken)
            .ConfigureAwait(false);
        return Ok();
    }

    /// <summary>Delete categories.</summary>
    [HttpPost("torrents/removeCategories")]
    public async Task<IActionResult> RemoveCategories(CancellationToken cancellationToken)
    {
        var unauthorised = Unauthorised();
        if (unauthorised is not null)
        {
            return unauthorised;
        }

        var form = await Request.ReadFormAsync(cancellationToken).ConfigureAwait(false);
        foreach (var name in form["categories"].ToString()
                     .Split('\n', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries))
        {
            await _engine.RemoveCategoryAsync(name, cancellationToken).ConfigureAwait(false);
        }

        return Ok();
    }

    /// <summary>Tag torrents. Sonarr calls this when "Add Series Tags" is enabled.</summary>
    [HttpPost("torrents/addTags")]
    public async Task<IActionResult> AddTags(CancellationToken cancellationToken)
    {
        var unauthorised = Unauthorised();
        if (unauthorised is not null)
        {
            return unauthorised;
        }

        var form = await Request.ReadFormAsync(cancellationToken).ConfigureAwait(false);
        var tags = form["tags"].ToString()
            .Split(',', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries);
        foreach (var hash in SplitHashes(form["hashes"]))
        {
            await _engine.AddTagsAsync(hash, tags, cancellationToken).ConfigureAwait(false);
        }

        return Ok();
    }

    /// <summary>
    /// Share limits, queue priority and forced start.
    /// </summary>
    /// <remarks>
    /// Accepted and ignored. StingStream's engine has no queue and enforces no share limits: it
    /// seeds until the arr decides the download may be removed, which is the behaviour the
    /// federated library wants anyway. Answering 200 rather than 404 keeps the arrs from logging
    /// a warning on every grab.
    /// </remarks>
    [HttpPost("torrents/setShareLimits")]
    [HttpPost("torrents/topPrio")]
    [HttpPost("torrents/bottomPrio")]
    [HttpPost("torrents/setForceStart")]
    [HttpPost("torrents/setAutoManagement")]
    public IActionResult Ignored() => Unauthorised() ?? Ok();

    // --- mapping ----------------------------------------------------------

    private static JsonObject ToQbtTorrent(TorrentView view) => new()
    {
        ["hash"] = view.Hash,
        ["name"] = view.Name,
        ["size"] = view.Size,
        ["total_size"] = view.Size,
        ["progress"] = view.Progress,
        ["eta"] = Eta(view),
        ["state"] = QbtState.From(view),
        ["category"] = view.Category,
        // The arrs still read the pre-3.x "label" when "category" is blank; sending both costs
        // nothing and makes the shim work with older tooling too.
        ["label"] = view.Category,
        ["tags"] = view.Tags,
        ["save_path"] = view.SavePath,
        ["content_path"] = view.ContentPath,
        ["ratio"] = view.Ratio,
        // -2 means "use the global limit", which app/preferences reports as disabled. Anything
        // >= 0 here would be read as a per-torrent limit the arrs then wait to be reached.
        ["ratio_limit"] = -2,
        ["seeding_time"] = view.SeedingSeconds,
        ["seeding_time_limit"] = -2,
        ["inactive_seeding_time_limit"] = -2,
        ["last_activity"] = DateTimeOffset.UtcNow.ToUnixTimeSeconds(),
        ["added_on"] = view.AddedOn,
        ["completion_on"] = view.Complete ? view.AddedOn : 0,
        ["dlspeed"] = view.DownloadRate,
        ["upspeed"] = view.UploadRate,
        ["downloaded"] = view.Downloaded,
        ["uploaded"] = view.Uploaded,
        ["amount_left"] = view.Remaining,
        ["completed"] = view.Size - view.Remaining,
        ["num_seeds"] = 0,
        ["num_leechs"] = 0,
        ["priority"] = 0,
        ["force_start"] = false,
        ["auto_tmm"] = false,
    };

    /// <summary>
    /// Seconds remaining, in qBittorrent's terms.
    /// </summary>
    /// <remarks>
    /// 8640000 (100 days) is qBittorrent's sentinel for "unknown or not applicable", and the arrs
    /// special-case exactly that value to mean "no estimate" rather than "100 days to go".
    /// </remarks>
    private static long Eta(TorrentView view)
    {
        const long Unknown = 8_640_000;
        if (view.Complete || view.Remaining <= 0)
        {
            return Unknown;
        }

        if (view.DownloadRate <= 0)
        {
            return Unknown;
        }

        var seconds = view.Remaining / view.DownloadRate;
        return seconds is <= 0 or > Unknown ? Unknown : seconds;
    }

    private static IEnumerable<string> SplitHashes(Microsoft.Extensions.Primitives.StringValues value)
        => value.ToString()
            .Split('|', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries)
            .Select(h => h.ToLowerInvariant());

    private static bool IsTrue(Microsoft.Extensions.Primitives.StringValues value)
    {
        var s = value.ToString();
        return string.Equals(s, "true", StringComparison.OrdinalIgnoreCase)
            || string.Equals(s, "1", StringComparison.Ordinal);
    }

    internal static string Invariant(long value) => value.ToString(CultureInfo.InvariantCulture);
}

/// <summary>
/// Maps MonoTorrent's <see cref="TorrentState"/> onto the qBittorrent state strings the arrs
/// switch on.
/// </summary>
/// <remarks>
/// The mapping matters more than it looks. Radarr's and Sonarr's <c>GetItems</c> turn these
/// strings into a <c>DownloadItemStatus</c>, and only <c>Completed</c> triggers an import:
/// <c>uploading</c>, <c>stalledUP</c>, <c>queuedUP</c>, <c>forcedUP</c>, <c>pausedUP</c> and
/// <c>stoppedUP</c> all mean "done". <c>stalledDL</c> and <c>missingFiles</c> surface as warnings
/// the user sees, so they are reserved for states that really are stuck.
/// </remarks>
public static class QbtState
{
    /// <summary>The qBittorrent state string for a torrent.</summary>
    public static string From(TorrentView view)
    {
        if (view.State == TorrentState.Error)
        {
            return "error";
        }

        if (view.Complete)
        {
            return view.State switch
            {
                TorrentState.Seeding => view.UploadRate > 0 ? "uploading" : "stalledUP",
                TorrentState.Paused or TorrentState.Stopped or TorrentState.Stopping => "stoppedUP",
                TorrentState.Hashing or TorrentState.HashingPaused => "checkingUP",
                _ => "stoppedUP",
            };
        }

        return view.State switch
        {
            TorrentState.Downloading => "downloading",
            TorrentState.Seeding => "uploading",
            TorrentState.Hashing or TorrentState.HashingPaused => "checkingDL",
            TorrentState.FetchingHashes => "checkingDL",
            // Waiting on metadata from a magnet link. The arrs map this to Queued when DHT is on
            // and to a warning when it is off, which is exactly right: with DHT off a trackerless
            // magnet is never going to resolve.
            TorrentState.Metadata => "metaDL",
            TorrentState.Paused => "pausedDL",
            TorrentState.Stopped or TorrentState.Stopping => "stoppedDL",
            TorrentState.Starting => "queuedDL",
            _ => "downloading",
        };
    }
}
