import { Redirect, useLocalSearchParams } from "expo-router";

/**
 * Libraries lived at `/settings/storage` until 2026-09-22, when the address was made to say what
 * the page is called. This keeps an old bookmark, and any `?focus=` it carries, working.
 *
 * A string href cast like `settings.tsx`'s: the typed-route list is generated by the dev server,
 * and a checkout whose copy predates the rename would otherwise fail to typecheck.
 */
export default function MovedToLibraries() {
  const params = useLocalSearchParams<Record<string, string>>();
  const query = new URLSearchParams(params).toString();
  return (
    <Redirect
      href={`/settings/libraries${query ? `?${query}` : ""}` as never}
    />
  );
}
