/**
 * Generated by `bun scripts/brand/generate.ts` from `scripts/brand/source.ts`.
 * Do not hand-edit -- change the source art and re-run the generator instead.
 *
 * The require()s are at module scope on purpose: eas-cli drops anything matching a
 * .gitignore rule from its upload, and a require inside a try/catch compiles to a
 * silent runtime throw rather than a failed build (see
 * `.claude/learned-facts/eas-archive-drops-gitignored-tracked-files`).
 * `assets/bundled-assets.test.ts` scans constants/ for these and pins them.
 */

import type { BrandAspects } from "@/components/brand/wordmarkLayout";

export const MARK_IMAGE = require("@/assets/brand/mark.png");
export const MARK_MONO_IMAGE = require("@/assets/brand/mark-mono.png");
export const WORDMARK_IMAGE = require("@/assets/brand/wordmark.png");
export const WORDMARK_LIGHT_IMAGE = require("@/assets/brand/wordmark-light.png");

/** Intrinsic width/height of each source image, for aspect-correct layout. */
export const BRAND_ASPECTS: BrandAspects = {
  mark: 400 / 674,
  wordmark: 856 / 151,
};

/** The mark's own gradient. NOT the UI accent -- that stays teal in theme.tokens.json. */
export const BRAND_ACCENT_FROM = "#3CDDFC";
export const BRAND_ACCENT_TO = "#6D5BF7";
export const BRAND_BG = "#0B0C0F";
