import { type ConfigPlugin, withSettingsGradle } from "expo/config-plugins";

/**
 * Makes the native autolinking cache notice the two things it currently cannot see: **`EXPO_TV`**
 * and **bun's lockfile**.
 *
 * ## The bug this exists to prevent
 *
 * `autolinkLibrariesFromCommand` (React Native's `ReactSettingsExtension`) caches the module list
 * in `android/build/generated/autolinking/autolinking.json` and decides whether to re-run the
 * `@react-native-community/cli config` command by SHA-256'ing a list of files — by default
 * `yarn.lock`, `package-lock.json`, `package.json` and `react-native.config.js`. Both halves of
 * that default are wrong here.
 *
 * * **We install with bun.** A dependency change that only moves `bun.lock` leaves every one of
 *   those hashes identical, so the stale module list survives it.
 * * **`EXPO_TV` is an environment variable, not a file.** `react-native.config.js` reads it and
 *   links `react-native-track-player`, `react-native-pager-view` and `react-native-volume-manager`
 *   *out* for TV — but the file itself never changes, so its hash never changes either. A TV build
 *   therefore writes a cache with those three missing, and the next **phone** build reuses it and
 *   produces an APK that passes every compile step and then dies on launch with
 *   `TurboModuleRegistry.getEnforcing(...): 'TrackPlayer' could not be found`. Nothing about the
 *   build says anything is wrong; M7 lost a full rebuild cycle to it.
 *
 * ## What it does
 *
 * `settings.gradle` writes the environment that `react-native.config.js` reads into
 * `android/build/autolinking-inputs/expo-env.properties`, then passes that file — plus bun's
 * lockfiles — to the `lockFiles` parameter the extension already exposes. Changing `EXPO_TV` now
 * changes a hash, which is all the cache ever needed to be told.
 *
 * Nothing is patched: `autolinkLibrariesFromCommand(command, workingDirectory, lockFiles)` is a
 * documented public overload, and the file list is the whole point of the third parameter.
 *
 * The generated `android/` is gitignored (matching upstream), which is why this is a config plugin
 * rather than a committed edit to `settings.gradle` — the same reason
 * `withGradleWrapperVersion.ts` exists. See `docs/APP-DEV.md`.
 */

/** The stock block `expo prebuild` writes, which this replaces. */
const STOCK = `extensions.configure(com.facebook.react.ReactSettingsExtension) { ex ->
  if (System.getenv('EXPO_USE_COMMUNITY_AUTOLINKING') == '1') {
    ex.autolinkLibrariesFromCommand()
  } else {
    ex.autolinkLibrariesFromCommand(expoAutolinking.rnConfigCommand)
  }
}`;

/** A string present only in our replacement, so re-running the plugin is a no-op. */
const MARKER = "autolinking-inputs/expo-env.properties";

const REPLACEMENT = `// --- what invalidates the autolinking cache -------------------------------------------------
//
// Written by plugins/withAutolinkingCacheKey.ts — read that file for why, and do not hand-edit
// this block: android/ is regenerated by \`expo prebuild\` and your change will vanish.
//
// React Native hashes yarn.lock / package-lock.json / package.json / react-native.config.js to
// decide whether the cached module list is still good. We install with **bun**, and
// react-native.config.js links three modules out when **EXPO_TV=1** — an env var, which hashes
// nothing. So a TV build leaves a cache that the next phone build reuses, and the phone APK dies
// at startup on a missing TrackPlayer. The environment goes into a file so it can be hashed like
// everything else.
def autolinkingRoot = new File(rootDir, "../")
def autolinkingEnvFile = new File(rootDir, "build/${MARKER}")
def autolinkingEnv = [
  "EXPO_TV=\${System.getenv('EXPO_TV') ?: ''}",
  "EXPO_USE_COMMUNITY_AUTOLINKING=\${System.getenv('EXPO_USE_COMMUNITY_AUTOLINKING') ?: ''}",
].join("\\n") + "\\n"
autolinkingEnvFile.parentFile.mkdirs()
// Written only when it differs, so an unchanged environment does not churn the file's mtime.
if (!autolinkingEnvFile.exists() || autolinkingEnvFile.getText("UTF-8") != autolinkingEnv) {
  autolinkingEnvFile.setText(autolinkingEnv, "UTF-8")
}

def autolinkingInputs = files(
  new File(autolinkingRoot, "yarn.lock"),
  new File(autolinkingRoot, "package-lock.json"),
  new File(autolinkingRoot, "bun.lock"),
  new File(autolinkingRoot, "bun.lockb"),
  new File(autolinkingRoot, "package.json"),
  new File(autolinkingRoot, "react-native.config.js"),
  autolinkingEnvFile,
)

extensions.configure(com.facebook.react.ReactSettingsExtension) { ex ->
  if (System.getenv('EXPO_USE_COMMUNITY_AUTOLINKING') == '1') {
    // The default command, spelled out because the overload that takes a file list has no way to
    // ask for it. \`cmd /c\` on Windows is what \`windowsAwareCommandLine\` does.
    def cli = ["npx", "@react-native-community/cli", "config"]
    def isWindows = System.getProperty("os.name").toLowerCase().contains("windows")
    ex.autolinkLibrariesFromCommand(
      isWindows ? ["cmd", "/c"] + cli : cli,
      autolinkingRoot,
      autolinkingInputs,
    )
  } else {
    ex.autolinkLibrariesFromCommand(
      expoAutolinking.rnConfigCommand,
      autolinkingRoot,
      autolinkingInputs,
    )
  }
}`;

/**
 * Rewrite the autolinking block, or explain why it could not be found.
 *
 * @param contents The generated `settings.gradle`.
 * @returns The rewritten contents.
 */
export function patchSettingsGradle(contents: string): string {
  if (contents.includes(MARKER)) return contents;
  if (!contents.includes(STOCK)) {
    throw new Error(
      "withAutolinkingCacheKey: the autolinking block in android/settings.gradle is not the one " +
        "this plugin knows how to rewrite — React Native or Expo has changed it. Do not ignore " +
        "this: without the rewrite, a build run with EXPO_TV=1 leaves an autolinking cache that " +
        "the next phone build reuses, and the phone APK dies at startup on a missing TrackPlayer. " +
        "Update plugins/withAutolinkingCacheKey.ts against the new block.",
    );
  }
  return contents.replace(STOCK, REPLACEMENT);
}

const withAutolinkingCacheKey: ConfigPlugin = (config) =>
  withSettingsGradle(config, (config) => {
    config.modResults.contents = patchSettingsGradle(
      config.modResults.contents,
    );
    return config;
  });

export default withAutolinkingCacheKey;
