#!/usr/bin/env bun
/**
 * Rebrand pass for the 32 non-English locale catalogues.
 *
 * translations/en.json is StingStream's own source of truth (see CLAUDE.md's translations
 * rule); every other file under translations/ was generated by Streamyfin's Crowdin project
 * and this fork is not on Crowdin, so nothing re-translates them for us. Two jobs, both
 * idempotent — safe to run again after a later pass edits en.json further:
 *
 *   1. Any locale string that still contains the literal word "Streamyfin" or "Jellyfin" (both
 *      product names, left untranslated by every translator the same way a brand name is, so
 *      they appear verbatim inside otherwise fully localised sentences) has the match replaced
 *      with "StingStream". This is a plain substring replace, not a key-by-key list or a real
 *      re-translation — brand.test.ts's guard scans every translations/*.json value, and a
 *      32-language retranslation is not something a script (or this work package) can do — so
 *      the mechanical swap is what keeps every locale's *product name* current without
 *      rewriting sentences this tooling cannot read. It also catches instances the English
 *      source no longer has an equivalent for (sv-SE's storage.app_usage said
 *      "Streamyfin {{usedSpace}}%" where every other locale just has the translated word for
 *      "App") and inflected forms in agglutinative languages, since the match has no word
 *      boundary: Finnish "Jellyfinille" → "StingStreamille", Hungarian "Jellyfinből" →
 *      "StingStreamből", Turkish "Jellyfin'i" → "StingStream'i".
 *   2. Any key present in a locale file but absent from the corresponding path in en.json is
 *      pruned. en.json is the only file WP11 (or anyone) edits by hand; when a future pass
 *      deletes a key there (e.g. WP-TV-LOGIN's removal of the pairing and companion_login
 *      namespaces once the companion-pairing feature is deleted), the 32 locales would
 *      otherwise carry it forever with no source to sync from. Empty objects left behind by
 *      pruning are removed too.
 *
 * Usage: bun scripts/rebrand-locales.ts [--check]
 *   --check   exit 1 if any locale would change, without writing (for CI / the loop's gates)
 */

import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

type Tree = { [key: string]: Tree | string };

const ROOT = join(__dirname, "..");
const LOCALES_DIR = join(ROOT, "translations");
const SOURCE_LOCALE = "en.json";
const CHECK_ONLY = process.argv.includes("--check");

// Case-insensitive: translators occasionally typed "JellyFin", and the replacement is a fixed
// brand name either way, so preserving the source casing would buy nothing.
const BRAND_WORD = /Streamyfin|Jellyfin/gi;

/** Replace every literal "Streamyfin"/"Jellyfin" with "StingStream" in every string leaf. */
function rebrandStrings(node: Tree | string): Tree | string {
  if (typeof node === "string") return node.replace(BRAND_WORD, "StingStream");
  const out: Tree = {};
  for (const [key, value] of Object.entries(node)) {
    out[key] = rebrandStrings(value);
  }
  return out;
}

/**
 * Remove any key from `node` that has no counterpart at the same path in `source`.
 * Recurses into nested objects that do have a counterpart; deletes ones that don't,
 * or whose source counterpart is no longer an object (shape drift). Mutates in place.
 */
function pruneToSource(node: Tree, source: Tree): void {
  for (const key of Object.keys(node)) {
    const sourceValue = source[key];
    if (sourceValue === undefined) {
      delete node[key];
      continue;
    }
    const nodeValue = node[key];
    if (typeof nodeValue === "object" && nodeValue !== null) {
      if (typeof sourceValue !== "object" || sourceValue === null) {
        delete node[key];
        continue;
      }
      pruneToSource(nodeValue, sourceValue);
      if (Object.keys(nodeValue).length === 0) delete node[key];
    }
  }
}

const source = JSON.parse(
  readFileSync(join(LOCALES_DIR, SOURCE_LOCALE), "utf8"),
) as Tree;

const localeFiles = readdirSync(LOCALES_DIR)
  .filter((name) => name.endsWith(".json") && name !== SOURCE_LOCALE)
  .sort();

let changedCount = 0;
const changedFiles: string[] = [];

for (const file of localeFiles) {
  const path = join(LOCALES_DIR, file);
  const original = readFileSync(path, "utf8");
  const data = JSON.parse(original) as Tree;

  const rebranded = rebrandStrings(data) as Tree;
  pruneToSource(rebranded, source);

  const next = `${JSON.stringify(rebranded, null, 2)}\n`;
  if (next !== original) {
    changedCount++;
    changedFiles.push(file);
    if (!CHECK_ONLY) writeFileSync(path, next);
  }
}

if (CHECK_ONLY) {
  if (changedCount > 0) {
    console.log(
      `❌ ${changedCount} locale file(s) need the rebrand pass: ${changedFiles.join(", ")}`,
    );
    console.log("   → run: bun scripts/rebrand-locales.ts");
    process.exit(1);
  }
  console.log(
    `✅ All ${localeFiles.length} locale files already match en.json's shape and carry no "Streamyfin"/"Jellyfin" literal.`,
  );
} else {
  console.log(
    changedCount > 0
      ? `✅ Rebranded ${changedCount}/${localeFiles.length} locale file(s): ${changedFiles.join(", ")}`
      : `✅ Nothing to do — all ${localeFiles.length} locale files already match.`,
  );
}
